# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

# the matrix of builds should cover each combination of Swift version
# and platform that is supported. The version of Swift used is specified
# by .swift-version, unless SWIFT_SNAPSHOT is specified.
matrix:
  include:
    - os: linux
      # Trusty build retained to provide 14.04 coverage (as paid support is still available)
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:4.1.3 SWIFT_SNAPSHOT=4.1.3
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:4.2.4 SWIFT_SNAPSHOT=4.2.4
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      # Note: Ubuntu 16.04
      env: DOCKER_IMAGE=swift:5.0.2-xenial
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      # Note: Kitura-WebSocket-NIO requires zlib
      env: DOCKER_IMAGE=swift:5.0.2-xenial KITURA_NIO=1 DOCKER_PACKAGES="libz-dev"
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      # Note: Ubuntu 18.04
      env: DOCKER_IMAGE=swift:5.0.2 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:5.0.2 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT KITURA_NIO=1 DOCKER_PACKAGES="libz-dev"
    - os: osx
      osx_image: xcode9.2
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: SWIFT_SNAPSHOT=4.1.2
    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: SWIFT_SNAPSHOT=4.2.1
    - os: osx
      osx_image: xcode10.2
      sudo: required
      env: SWIFT_SNAPSHOT=5.0.1 JAZZY_ELIGIBLE=true
    - os: osx
      osx_image: xcode10.2
      sudo: required
      env: SWIFT_SNAPSHOT=5.0.1 KITURA_NIO=1
    - os: osx
      osx_image: xcode11
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT
    - os: osx
      osx_image: xcode11
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT KITURA_NIO=1

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
